- name: configure inetRouter
  hosts: debian_vm
  tasks:
    - name: install knockd
      become: true
      ansible.builtin.apt:
        name:  knockd
        state: present
        update_cache: true
    - name: copy iptables config
      become: true
      ansible.builtin.template:
        src: iptables
        dest: /etc/iptables.rules
        owner: root
        group: root
        mode: 0600
    - name: copy knockd config
      become: true
      ansible.builtin.template:
        src: knockd.conf
        dest: /etc/knockd.conf
        owner: root
        group: root
        mode: 0600
    - name:
      become: true
      ansible.builtin.lineinfile:
        path: /etc/default/knockd
        regexp: START_KNOCKD=0
        line: START_KNOCKD=1
    


- name: set up forward packages across routers
  become: true
  hosts: routers
  tasks:
    - name: set up forward packages across routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present

- name: starting nginx
  hosts: centralServer
  tasks:
    - name: install nginx
      become: true
      ansible.builtin.apt:
        name:  nginx
        state: present
        update_cache: true
        
    - name: Start and enable nginx service
      service:
        name: nginx
        state: started
        enabled: true

- name: configure inetRouter2
  become: true
  hosts: inetRouter2
  tasks:
    - name: Forward port 80 to centralServer:8080
      iptables:
        table: nat
        chain: PREROUTING
        protocol: tcp
        match: tcp
        destination_port: "8080"
        jump: DNAT
        to_destination: "192.168.50.34:80"

    - name: Allow output traffic to port 8080
      iptables:
        table: nat
        chain: OUTPUT
        protocol: tcp
        destination_port: "8080"
        jump: DNAT
        to_destination: "192.168.50.34:80"

    - name: Enable masquerade for internal net
      iptables:
        table: nat
        chain: POSTROUTING
        jump: MASQUERADE

    - name: Create static route to internal network
      shell: "ip route add 192.168.50.0/24 via 192.168.50.33"
      ignore_errors: yes
