---
- name: Set up PXE Server
  hosts: pxeserver
  vars_files:
    - defaults/main.yaml
  tasks:
  #sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
  - name: set up repo
    become: true
    ansible.builtin.replace:
      path: "/etc/yum.repos.d/{{ item }}"
      regexp: 'mirrorlist'
      replace: '#mirrorlist'
    with_items:
    - CentOS-Linux-AppStream.repo
    - CentOS-Linux-BaseOS.repo
    - CentOS-Linux-ContinuousRelease.repo
    - CentOS-Linux-Debuginfo.repo
    - CentOS-Linux-Devel.repo
    - CentOS-Linux-Extras.repo
    - CentOS-Linux-FastTrack.repo
    - CentOS-Linux-HighAvailability.repo
    - CentOS-Linux-Media.repo
    - CentOS-Linux-Plus.repo
    - CentOS-Linux-PowerTools.repo
    - CentOS-Linux-Sources.repo

#sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
  - name: set up repo
    become: true
    ansible.builtin.replace:
      path: "/etc/yum.repos.d/{{ item }}"
      regexp: '#baseurl=http://mirror.centos.org'
      replace: 'baseurl=http://vault.centos.org'
    with_items:
    - CentOS-Linux-AppStream.repo
    - CentOS-Linux-BaseOS.repo
    - CentOS-Linux-ContinuousRelease.repo
    - CentOS-Linux-Debuginfo.repo
    - CentOS-Linux-Devel.repo
    - CentOS-Linux-Extras.repo
    - CentOS-Linux-FastTrack.repo
    - CentOS-Linux-HighAvailability.repo
    - CentOS-Linux-Media.repo
    - CentOS-Linux-Plus.repo
    - CentOS-Linux-PowerTools.repo
    - CentOS-Linux-Sources.repo

  - name: install softs on CentOS
    become: true
    ansible.builtin.yum:
      name:
      - vim
      - wget
      - epel-release
      - httpd
      - tftp-server
      - dhcp-server
      state: present
      update_cache: true

#Скачивание образа CentOS-8.4.2105-x86_64-dvd1.iso
#Скачиваться будет долго, размер файла больше 9 ГБ. 
  - name: Download ISO image CentOS 8.4.2105
   # become: true
    ansible.builtin.get_url:
      url: https://mirror.nsc.liu.se/centos-store/centos/8.4.2105/isos/x86_64/CentOS-8.4.2105-x86_64-dvd1.iso
#      url: https://mirrors.aliyun.com/centos-vault/centos/8.4.2105/isos/x86_64/CentOS-8.4.2105-x86_64-dvd1.iso?spm=a2c6h.25603864.0.0.36cf7f8blK42Uf
      dest: /home/vagrant/CentOS-8.4.2105-x86_64-dvd1.iso
      mode: '0755'

#Создание каталога /iso и назначение прав 755  
  - name: Create ISO directory
    become: true
    file:
      state: directory
      path: /iso
      #mode: '0755'

#Монтируем образ в каталог /mnt
  - name: Mount ISO image
    become: true
    mount:
      path: /mnt
      src: /root/CentOS-8.4.2105-x86_64-dvd1.iso
      fstype: iso9660
      opts: ro,loop
      state: mounted

#Копируем все файлы из каталога /mnt в /iso
  - name: copy ALL files from /mnt to /iso
    become: true
    copy:
      src: /mnt/
      dest: /iso
      remote_src: yes 
      directory_mode: yes

#Копируем конфгурационный файл pxeboot.conf (Файл должен быть предварительно создан в каталаге templates)
  - name: set up httpd config
    become: true
    template:
      src: pxeboot.conf
      dest: /etc/httpd/conf.d/pxeboot.conf 
      owner: root
      group: root
      mode: 0640

#Перезупускаем httpd и добавляем службу в автозагрузку
  - name: restart httpd
    become: true
    ansible.builtin.service:
      name: httpd
      state: restarted
      enabled: true


# Настройка TFTP-сервера
  - name: Create TFTP directory
    become: true
    file:
      path: /var/lib/tftpboot/pxelinux.cfg
      state: directory

#Копируем файл-меню на сервер
  - name: set up pxelinux
    become: true
    template:
      src: default
      dest: /var/lib/tftpboot/pxelinux.cfg/default
      owner: root
      group: root
      mode: 0644
  
  #Извлекаем файлы из RPM-пакета
  - name: extract packages syslinux
    become: true
    shell: rpm2cpio /iso/BaseOS/Packages/syslinux-tftpboot-6.04-5.el8.noarch.rpm | cpio -dimv
    
  #Копируем файлы в каталог /var/lib/tftpboot/
  - name: copy files to TFTP share
    become: true
    copy:
      src: /home/vagrant/tftpboot/{{ item }}
      dest: /var/lib/tftpboot/{{ item }}
      mode: '0644'
      remote_src: true
    with_items:
      - pxelinux.0
      - ldlinux.c32
      - libmenu.c32
      - libutil.c32
      - menu.c32
      - vesamenu.c32
  
  #Копируем файлы в каталог /var/lib/tftpboot/
  - name: copy initrd and vmlinuz files to TFTP share
    become: true
    copy:
      src: /iso/images/pxeboot/{{ item }}
      dest: /var/lib/tftpboot/{{ item }}
      mode: '0755'
      remote_src: true
    with_items:
      - initrd.img
      - vmlinuz
  
  #Перезапускаем TFTP-сервер и добавляем его в автозагрузку 
  - name: restart tftp-server
    become: true
    ansible.builtin.service:
      name: tftp.service
      state: restarted
      enabled: true
  
  
  #Настройка DHCP-сервера
  #Копирование файла конфигурации DHCP-сервера
  - name: set up dhcp-server
    template:
      src: dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
      mode: '0644'
  
  #Перезапуск службы и добавление в автозагрузку
  - name: restart dhcp-server
    ansible.builtin.service:
      name: dhcpd
      state: restarted
      enabled: true
  
  
  #Отправка kickstart-файла
  - name: copy ks.cfg
    template:
      src: ks.cfg
      dest: /iso/ks.cfg
      owner: root
      group: root
      mode: 0755
  
  
