---
all:
  hosts:
    inetRouter:
      ansible_host: 192.168.50.10
      ansible_user: vagrant
    centralRouter:
      ansible_host: 192.168.50.11
      ansible_user: vagrant
    office1Router:
      ansible_host: 192.168.50.20
      ansible_user: vagrant
    office2Router:
      ansible_host: 192.168.50.30
      ansible_user: vagrant
    centralServer:
      ansible_host: 192.168.50.12
      ansible_user: vagrant
  children:
    routers:
      hosts:
        inetRouter:
        centralRouter:
        office1Router:
        office2Router:
    centos_vm:
      hosts:
        centralRouter:
        centralServer:

#[routers]
#office2Router ansible_host=192.168.50.30 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/office2Router/virtualbox/private_key
