Vagrant.configure("2") do |config|
    # Base VM OS configuration.
    config.vm.box = "centos/7"
    config.vm.box_version = "2004.01"
    config.vm.provider :virtualbox do |v|
        v.memory = 512
        v.cpus = 1
    end
    # Define two VMs with static private IP addresses.
    boxes = [
        { :name => "web",
            :ip => "192.168.50.10",
        },
        { :name => "log",
            :ip => "192.168.50.15",
        }
    ]
# Provision each of the VMs.
    boxes.each do |opts|
        config.vm.define opts[:name] do |config|
            config.vm.hostname = opts[:name]
            config.vm.network "private_network", ip: opts[:ip]
        config.vm.provision "shell" do |s|
            ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
            s.inline = <<-SHELL
                echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
                mkdir /root/.ssh/
                echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
            SHELL
        end

            if opts[:name] == boxes.last[:name]
                config.vm.provision "ansible" do |ansible|
                    ansible.playbook = "./playbook/site.yml"
                    ansible.inventory_path = "./playbook/inventory/prod.yml"
                    ansible.host_key_checking = "false"
                    ansible.limit = "all"
                    ansible.raw_arguments  = [
                          "--connection=paramiko"
                    ]
                end
            end
        end
    end
end
